### ISSUE TITLE
Request: adding 'mirror mode' for lefties?

### ISSUE THREAD

**Issue by sabzingeur** [mikehadlow/gtr-cof#18]
Hi there!
Thank you so much for the clean, easy to use and intuitive app. I have 1 request, as a lefty, I spend most of my time looking at other righties' neck when learning new things on the guitar, and it is exactly as I am looking at myself in the mirror.
So basically what I'd love to be implemented is another option for the current left-handed mode, but with the low E on top (some apps call it the 'flip the nut' mode).

All the best!

**Comment by mikehadlow** [comment]
Hi @sabzingeur,
Thanks for the great request. What would be best...
1) leaving the existing checkbox for 'left-handed fretboard' and adding a new checkbox for 'flip the nut'?
2) Make the selection a radio button list: 'normal', 'left-handed', 'mirrored'?
I think I prefer option (1), but I'm not left-handed, so I'll defer the choice to you :)

**Comment by sabzingeur** [comment]
Hi Mike,
Thanks for the lightning quick response. As a lefty I'd say the most intuitive layout is to treat the 'mirror mode' (lefty + flip the nut) as the default for lefties, since that is how we lefties always see the guitar neck of other righties in videos; whereas chords and pallete charts specially designed for lefties are custom-made and may vary.
However you should also have to consider the existing user-base of lefties who are already used to using the app as it is right now.
If we think about it a bit more, then righties can also benefit from a 'flip the nut' option as well (which put the low E on top and reverse the string orders from traditional layout, software like Rocksmith offer such options. If I'm not mistaken, the traditional layout with the low E at the bottom was created specifically because it is confusing and hard for normal learners (righties) to instinctively read their teacher's hand.
Last of all, because the app is designed for desktop and laptop users this is not so relevant because of the landscape layout, but for smartphones for example, the 'upright' neck layout is the only layout needed as both righties and lefties can study the layout and work out their ways on the fret-board with ease.

**Comment by mikehadlow** [comment]
OK, I've done the simplest thing possible. I've just added a 'flip nut' checkbox, which is kinda what you suggested right? As you said, this gives the greatest number of options for all users. Hope you like it, and thanks again for an excellent suggestion.
