### ISSUE TITLE
building without vscode

### ISSUE THREAD

**Issue by nchase** [mikehadlow/gtr-cof#19]
is there currently a way to build this project without using the vscode editor?

if not, I can rig one up.

**Comment by mikehadlow** [comment]
Hi @nchase,
I use VS Code, but it would be great if you wanted to add other build methods to the README.md file in a pull request.

**Comment by l3nz** [comment]
I created pull #25 so that you can have a "getting started" without VSCode. This actually put me off at the beginning.

**Comment by nchase** [comment]
Thanks @l3nz! This put me off too, and then I didn't have the time to get back to it.
