### ISSUE TITLE
Using different note names

### ISSUE THREAD

**Issue by l3nz** [mikehadlow/gtr-cof#22]
Thanks for your excellent tool!

I think it would be nice to have a different set of note names - Italians use "Do re mi fa sol la si", Germans use H instead of B but have different names for e.g. C#.

**Comment by mikehadlow** [comment]
I've decided that the whole issue of internationalization is too big a task for me and one that I'm not qualified for, so I'd encourage users from non-English speaking countries to fork a local version of Guitar Dashboard.
