### ISSUE TITLE
Chromatic circle improvements

### ISSUE THREAD

**Issue by ibalashov** [mikehadlow/gtr-cof#35]
1. Start on C at the top (this is more common than A, and aligns with wikipedia)
2. Display chords on chromatic circle (maj, min, dim, etc.), with fretboard map (which comes automatically I guess).

**Comment by mikehadlow** [comment]
Thanks for this. I'm not quite sure what you mean by "Display chords on chromatic circle"? Chords _are_ displayed there. Also "with fretboard map"? The chords displayed on the chromatic circle are also displayed on the fretboard.

I'm guessing this could be bug if you're not seeing the chords displayed. What device/OS/browser are you using?

**Comment by ibalashov** [comment]
Actually, I do see the chords, sorry to have mislead you. But it I need to watch the introductory video one more time :)

Also the positioning of the circles applies to both, not just to chromatic, just noticed.

**Comment by mikehadlow** [comment]
OK, no  worries, thanks for the update. I think rather than just defaulting with the C at the top, which would be confusing for people who were already used to the existing default, how about having an option?

**Comment by ibalashov** [comment]
Yes, I agree.

**Comment by mikehadlow** [comment]
C is now at top centre by default (can switch back to A in settings)
