### ISSUE TITLE
can't add tuning with accidental note

### ISSUE THREAD

**Issue by sugizo** [mikehadlow/gtr-cof#39]
can't add tuning with accidental note, already tested add this on tuning-module.ts :

        { tuning: "G#CEG#CE", dots: guitarDots, description: "test0" },
        { tuning: "AbCEAbCE", dots: guitarDots, description: "test1" },
        { tuning: "A♭CEA♭CE", dots: guitarDots, description: "test2" },

what i expected ?
can add major thirds tuning that consists of G#-C-E-G#-C-E

**ref:**
https://en.wikipedia.org/wiki/Major_thirds_tuning

thanks

**Comment by mikehadlow** [comment]
That's correct, the parser for the tuning string currently only handles naturals. Thanks for adding this issue, it'll serve as a good placeholder to remind me to add flats and sharps.

**Comment by sugizo** [comment]
in order to achieve this, perhaps you can use '-' as separated signed for the note
instead G#CEG#CE you can use G#-C-E-G#-C-E
and use logic to iterate between it's strings and use '-' as a separator note

as an example given above for accidental tuning is have an alias you must consider e.g.
G# = A♭ = Ab (some use b as a flat because ♭ dont have in keyboard tuts)
