### ISSUE TITLE
can't add chromatic scale

### ISSUE THREAD

**Issue by sugizo** [mikehadlow/gtr-cof#40]
can't add chromatic scale, already tried on music-module.ts
`
        { name: "Chromatic", intervals: new mod.Mod([true, true, true, true, true, true, true, true, true, true, true, true]), modes: [{ name: 'Chromatic', index: 0}], defaultModeIndex: 0 },
`

seems can't have the scale more than 10 notes
no error occured, but the result is not expected (the scale didnt change when click on chromatic scale drop down menu)

**Comment by mikehadlow** [comment]
There's not much benefit to having a chromatic scale in guitar dashboard. It wouldn't show you anything useful, other than that any note is a scale note. The internal logic will probably fail over a certain number of scale notes, although I haven't experimented with more than 8 personally. The note naming starts to fall over pretty quickly with denser scales.

**Comment by sugizo** [comment]
yeah, you right

what i want to achieve is to show all the notes with the selected 'tuning' in guitar fretboard, so that user can have a complete view of fretboard in order to memorize it (fretboard memorization)

and the best way to achieve it, is to add the chromatic scale 

or have another idea how to achieve it, is fine by me

thanks
