### ISSUE TITLE
add new tuning to consider (only natural note)

### ISSUE THREAD

**Issue by sugizo** [mikehadlow/gtr-cof#43]
tuning-module.ts
// (open tuning, cross note tuning) : best to play harmonization or as rhythm guitar (playing chord with just minimal finger 1 or two)
        { tuning: "DFACEG", dots: guitarDots, description: "Dm9/11" },
        { tuning: "CGCDGC", dots: guitarDots, description: "Csus2" },
        { tuning: "DADEAB", dots: guitarDots, description: "D6sus2" },
        { tuning: "DADEAC", dots: guitarDots, description: "D7sus2" },
        { tuning: "DADFAD", dots: guitarDots, description: "Cross Note D" },
        { tuning: "DADFAB", dots: guitarDots, description: "Dm6" },
        { tuning: "DADFAC", dots: guitarDots, description: "Dm7" },
        { tuning: "DADGAD", dots: guitarDots, description: "Dsus4" },

// regular tuning, best to learn note because it's symetrical, another useful tuning is major third and minor third but right now your code cant support accidental note to add major third and minor third tuning
        { tuning: "BFBFBF", dots: guitarDots, description: "Augmented Fourths" },

// another bass standard tuning for 5th strings and 6 strings
        { tuning: "EADGC", dots: guitarDots, description: "Bass 5 Strings Standard High" },
        { tuning: "BEADG", dots: guitarDots, description: "Bass 5 Strings Standard Low" },
        { tuning: "BEADGC", dots: guitarDots, description: "Bass 6 Strings Standard" },

thanks

**Comment by mikehadlow** [comment]
Thanks for this. Easy to add, I'll try and do it reasonably soon.

**Comment by mikehadlow** [comment]
Closing this issue. I think it's not a good idea to add every possible tuning. Instead better to add a feature to allow users to input their own custom tuning.
