### ISSUE TITLE
no 7 in chord progression

### ISSUE THREAD

**Issue by sugizo** [mikehadlow/gtr-cof#46]
on harmonic minor scale : 
- harmonic minor no 7 on viidim
- lydian #2 no 7 on iidim
- ionian #5 no 7 on vdim
- superlocrian no 7 on idim
- dorian #4 no 7 on ivdim
- phrygian dominant no 7 on iiidim
- locrian #6 no 7 on vidim

not checked the others scale, seems have the same issue
the 7 indicate you played it with seventh chord, but it's a choice, you can play in a triad too, but if you know the formula of building chord or chord progression not everything is common e.g.
**major scale/ionian mode**
135 = ceg = c major scale (major)
125 = cdg = csus2 (suspended)
145 = cfg = csus4 (suspended)
1357 = cegb = cmaj7 (major)
1356 = cega = c6 (dominant)
etc

**suggestion** 
- better to remove 7 on chord progression (recommended) 
or
- not have chord progression at all (not recommended, because chord in roman numeral is a big help for newbie)

thanks

**Comment by mikehadlow** [comment]
I agree, having the 7th indicated is probably confusing. Agreed it should be removed, or at least made optional.
