### ISSUE TITLE
Use GitHub Actions to build Typescript and publish site

### ISSUE THREAD

**Issue by mikehadlow** [mikehadlow/gtr-cof#61]

**Comment by mikehadlow** [comment]
Done.
gtr-cof.js and gtr-cof.js.map no longer maintained in source code.

**Comment by peaceiris** [comment]
I recommend you to remove `package-lock.json` in the `.gitignore` and add it under Git control for stable CI.

cf. https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json

**Comment by mikehadlow** [comment]
Thanks for that, really good advice.
