### ISSUE TITLE
Sharp and Flat Key Display does not work

### ISSUE THREAD

**Issue by poww10s** [mikehadlow/gtr-cof#62]
On the most recent version of Chrome, android as well as Windows 10, on PC, Mobile and my Laptop

The scale will only change to display the natural keys and their modes, but not any key that is a sharp or flat key!
Something seems to not be loading into the page if I check via chrome debug
and there is a console error:
`Uncaught naturalIndex is not valid: 11`

**Comment by mikehadlow** [comment]
Fixed with 86d6bb92
Many thanks for spotting and reporting this!
